Repository SamanthaGuillemette/SOEN390, pull requests merged in 2022-03, with the labels that each got.

#197 Table cell for header "ID" aligned center
  Admin-app/src/components/PatientList/index.js
Labels: Bug, Pull Request

#199 Bug Fix #170: Was missing call to setPrioriyFlag in useEffect. Also …
  Admin-app/src/components/PatientProfile/index.js
Labels: Bug, Pull Request

#200 Dashboard Cards - CSS
  Admin-app/src/screens/Dashboard/Dashboard.css
  Admin-app/src/screens/Dashboard/index.js
Labels: Pull Request

#198 Fixed navbar and layout for chat
  Client-app/src/components/Chat/Chat.css
  Client-app/src/components/Chat/index.js
Labels: Pull Request

#205 Implementation for #139, #173, #203, and #204
  Admin-app/src/backend/firebaseDoctorUtilities.js
  Admin-app/src/backend/firebasePatientUtilities.js
  Admin-app/src/backend/firebaseUtilities.js
  Admin-app/src/components/DoctorList/index.js
  Admin-app/src/components/DropdownDoctor/index.js
  Admin-app/src/components/PatientList/index.js
  Admin-app/src/components/PatientProfile/PatientProfile.css
  Admin-app/src/components/PatientProfile/index.js
  Admin-app/src/data/doctors.json
Labels: Pull Request

#210 Issues #16 and #171 implementation
  Admin-app/package-lock.json
  Admin-app/package.json
  Admin-app/src/backend/firebasePatientUtilities.js
  Admin-app/src/components/PatientList/PatientList.css
  Admin-app/src/components/PatientList/index.js
  Admin-app/src/components/PatientProfile/index.js
  Client-app/package-lock.json
Labels: Pull Request

#213 Scroll bug fix
  Client-app/package-lock.json
  Client-app/src/App.js
  Client-app/src/components/Chat/Chat.css
  Client-app/src/components/Chat/index.js
  Client-app/src/components/SignIn/index.js
  Client-app/src/components/SignUp/index.js
  Client-app/src/screens/Chatting/index.js
Labels: Pull Request

#216 Shared Modal component
  Admin-app/package-lock.json
  Admin-app/src/components/SignIn/index.js
  Admin-app/src/components/SignUp/index.js
  Client-app/src/components/SignIn/index.js
  Client-app/src/components/SignUp/index.js
Labels: Pull Request

#209 Quang editable client profile
  Client-app/src/App.js
  Client-app/src/components/ClientProfile/ClientProfile.css
  Client-app/src/components/ClientProfile/ClientProfile.test.js
  Client-app/src/components/ClientProfile/ProfileEditModal.js
  Client-app/src/components/ClientProfile/index.js
  Client-app/src/components/SignIn/index.js
  Client-app/src/index.js
  Client-app/src/store/authSlice.js
  Client-app/src/store/userInfoSlice.js
Labels: Pull Request

#224 Feature/diary for issue #157
  Client-app/src/App.js
  Client-app/src/components/Dashboard/index.js
  Client-app/src/components/Diary/DiaryEntryModal.js
  Client-app/src/components/Diary/DiarySuccessAlert.js
  Client-app/src/components/Diary/DiaryTable.css
  Client-app/src/components/Diary/DiaryTable.test.js
  Client-app/src/components/Diary/index.js
  Client-app/src/screens/Diary/index.js
Labels: Pull Request

#226 Fixes to notification tests
  Admin-app/src/components/Notifications/Notifications.test.js
Labels: Pull Request

#227 CSS Changes
  Admin-app/src/components/COVID-19Button/COVID-19Button.css
  Admin-app/src/components/COVID-19Button/index.js
  Admin-app/src/components/DoctorList/DoctorList.test.js
  Admin-app/src/components/DoctorList/index.js
  Admin-app/src/components/DropdownDoctor/DropdownDoctor.css
  Admin-app/src/components/DropdownDoctor/index.js
  Admin-app/src/components/DropdownStatus/DropdownStatus.css
  Admin-app/src/components/DropdownStatus/index.js
  Admin-app/src/components/EventButton/EventButton.css
  Admin-app/src/components/EventButton/index.js
  Admin-app/src/components/Notifications/Notifications.css
  Admin-app/src/components/Notifications/Notifications.test.js
  Admin-app/src/components/Notifications/index.js
  Admin-app/src/components/PatientList/Patients-Table.css
  Admin-app/src/components/PatientList/index.js
  Admin-app/src/components/PatientProfile/PatientProfile.css
  Admin-app/src/components/PatientProfile/index.js
  Admin-app/src/components/SidebarItems/SidebarItems.css
  Admin-app/src/components/SidebarItems/index.js
  Admin-app/src/components/SignIn/index.js
  Admin-app/src/components/SignUp/SignUp.css
  Admin-app/src/components/SignUp/index.js
  Admin-app/src/components/SmallStatBox/SmallStatBox.css
  Admin-app/src/components/SmallStatBox/SmallStatBox.test.js
  Admin-app/src/components/SmallStatBox/index.js
  Admin-app/src/components/UpcomingEvents/UpcomingEvents.css
  Admin-app/src/components/UpcomingEvents/UpcomingEvents.test.js
  Admin-app/src/components/UpcomingEvents/index.js
  Admin-app/src/screens/Dashboard/Dashboard.css
  Admin-app/src/screens/Dashboard/Dashboard.test.js
  Admin-app/src/screens/Dashboard/index.js
  Admin-app/src/screens/Inbox/Chat.css
  Admin-app/src/screens/Inbox/index.js
  Admin-app/src/screens/Patients/Patients.css
  Admin-app/src/screens/Patients/index.js
  Client-app/src/components/BottomNav/BottomNav.css
  Client-app/src/components/BottomNav/BottomNav.test.js
  Client-app/src/components/BottomNav/index.js
  Client-app/src/components/Chat/Chat.css
  Client-app/src/components/Chat/index.js
  Client-app/src/components/ClientProfile/ClientProfile.css
  Client-app/src/components/ClientProfile/index.js
  Client-app/src/components/DropdownConfirmation/Dropdown.test.js
  Client-app/src/components/DropdownConfirmation/index.js
  Client-app/src/components/QR/QR.css
  Client-app/src/components/QR/index.js
  Client-app/src/components/SignIn/index.js
  Client-app/src/components/SignIn/signin.css
  Client-app/src/components/SignUp/SignUp.css
  Client-app/src/components/SignUp/index.js
  Client-app/src/components/SymptomsTable/SymptomsTable.css
  Client-app/src/components/SymptomsTable/index.js
Labels: Pull Request

#228 Chat notifications
  Admin-app/src/components/Chat/Chat.css
  Admin-app/src/components/Chat/Chat.test.js
  Admin-app/src/components/Chat/index.js
  Admin-app/src/components/ChatList/ChatList.css
  Admin-app/src/components/ChatList/ChatList.js
  Admin-app/src/components/ChatList/ChatList.test.js
  Admin-app/src/components/Navbar/index.js
  Admin-app/src/screens/Inbox/index.js
  Client-app/package-lock.json
  Client-app/package.json
  Client-app/src/components/Chat/Chat.css
  Client-app/src/components/Chat/Chat.test.js
  Client-app/src/components/Chat/index.js
  Client-app/src/screens/Chatting/index.js
Labels: Pull Request

#231 Refactoring patient list
  Admin-app/src/components/COVID-19Button/index.js
  Admin-app/src/components/ChatList/ChatList.js
  Admin-app/src/components/DashboardCards/DashboardCards.css
  Admin-app/src/components/DashboardCards/DashboardCards.test.js
  Admin-app/src/components/DashboardCards/index.js
  Admin-app/src/components/DashboardStats/DashboardStats.test.js
  Admin-app/src/components/DashboardStats/index.js
  Admin-app/src/components/DoctorList/index.js
  Admin-app/src/components/DropdownDoctor/index.js
  Admin-app/src/components/DropdownStatus/index.js
  Admin-app/src/components/EventButton/index.js
  Admin-app/src/components/PatientList/SingleRow.js
  Admin-app/src/components/PatientList/index.js
  Admin-app/src/components/PatientProfile/index.js
  Admin-app/src/components/QR/index.js
  Admin-app/src/components/SignIn/index.js
  Admin-app/src/components/SignUp/index.js
  Admin-app/src/components/UpcomingEvents/index.js
  Admin-app/src/screens/Dashboard/Dashboard.css
  Admin-app/src/screens/Dashboard/Dashboard.test.js
  Admin-app/src/screens/Dashboard/index.js
  Client-app/src/components/BottomNav/index.js
  Client-app/src/components/ClientProfile/index.js
  Client-app/src/components/Dashboard/index.js
  Client-app/src/components/Diary/index.js
  Client-app/src/components/DoctorInfo/index.js
  Client-app/src/components/Navbar/index.js
  Client-app/src/components/QR/index.js
  Client-app/src/components/SignUp/index.js
  Client-app/src/components/SymptomsTable/index.js
  Client-app/src/screens/Chatting/index.js
Labels: Pull Request

#229 added JSdocs follows Google standards
  Admin-app/package-lock.json
  Admin-app/src/components/AppBody/index.js
  Admin-app/src/components/COVID-19Button/index.js
  Admin-app/src/components/Calendar/index.js
  Admin-app/src/components/Charts/DoughnutChart.js
  Admin-app/src/components/Charts/LineChart.js
  Admin-app/src/components/DoctorList/index.js
  Admin-app/src/components/DropdownDoctor/index.js
  Admin-app/src/components/DropdownStatus/index.js
  Admin-app/src/components/Event/EventDetails.js
  Admin-app/src/components/Event/EventList.js
  Admin-app/src/components/Event/index.js
  Admin-app/src/components/EventButton/index.js
  Admin-app/src/components/Navbar/index.js
  Admin-app/src/components/News/NewsDetails.js
  Admin-app/src/components/News/NewsList.js
  Admin-app/src/components/News/index.js
  Admin-app/src/components/Notifications/index.js
  Admin-app/src/components/PatientList/index.js
  Admin-app/src/components/PatientProfile/index.js
  Admin-app/src/components/QR/index.js
  Admin-app/src/components/Sidebar/index.js
  Admin-app/src/components/SidebarItems/index.js
  Admin-app/src/components/SignIn/index.js
  Admin-app/src/components/SignUp/index.js
  Admin-app/src/components/SmallStatBox/index.js
  Admin-app/src/components/UpcomingEvents/index.js
  Admin-app/src/screens/Appointments/index.js
  Admin-app/src/screens/Dashboard/index.js
  Admin-app/src/screens/Inbox/index.js
  Admin-app/src/screens/Patients/index.js
  Client-app/src/App.js
  Client-app/src/backend/firebase.js
  Client-app/src/components/BottomNav/index.js
  Client-app/src/components/Chat/index.js
  Client-app/src/components/ClientProfile/ProfileEditModal.js
  Client-app/src/components/ClientProfile/index.js
  Client-app/src/components/Dashboard/index.js
  Client-app/src/components/Diary/DiaryEntryModal.js
  Client-app/src/components/Diary/index.js
  Client-app/src/components/DoctorInfo/index.js
  Client-app/src/components/Loading/index.js
  Client-app/src/components/Navbar/index.js
  Client-app/src/components/Notifications/index.js
  Client-app/src/components/QR/index.js
  Client-app/src/components/SignIn/index.js
  Client-app/src/components/SignUp/index.js
  Client-app/src/components/SymptomsTable/index.js
  Client-app/src/index.js
  Client-app/src/screens/Chatting/index.js
  Client-app/src/screens/Dashboard/index.js
  Client-app/src/screens/Diary/index.js
  Client-app/src/screens/MyDoctor/index.js
  Client-app/src/screens/Notifications/index.js
  Client-app/src/screens/Profile/index.js
  Client-app/src/screens/QR/index.js
  Client-app/src/screens/Symptoms/index.js
Labels: Task, Pull Request

#232 Update status
  Client-app/src/App.js
  Client-app/src/backend/firebase.js
  Client-app/src/components/Dashboard/index.js
  Client-app/src/components/UpdateStatus/StatusModal.js
  Client-app/src/components/UpdateStatus/SymptomsTable.js
  Client-app/src/components/UpdateStatus/UpdateStatus.css
  Client-app/src/components/UpdateStatus/index.js
  Client-app/src/screens/Status/index.js
  Client-app/src/store/authSlice.js
Labels: User Story

#242 fixed merge conflict in QR client app
  Client-app/package-lock.json
  Client-app/src/components/QR/index.js
Labels: Pull Request

#240 QA Develop
  Admin-app/cypress.json
  Admin-app/cypress/integration/FinalQA.spec.js
  Admin-app/cypress/integration/QADashboard.spec.js
  Admin-app/cypress/integration/untitled.spec.js
  Admin-app/src/components/Chat/index.js
  Admin-app/src/components/ChatList/ChatList.js
  Admin-app/src/components/DashboardCards/index.js
  Admin-app/src/components/DashboardStats/index.js
  Client-app/cypress.json
  Client-app/cypress/integration/DashboardQA.spec.js
  Client-app/cypress/integration/FinalQA.spec.js
  Client-app/cypress/support/index.js
  Client-app/src/components/Dashboard/index.js
  Client-app/src/components/QR/index.js
  Client-app/src/components/UpdateStatus/SymptomsTable.js
  Client-app/src/components/UpdateStatus/index.js
Labels: Pull Request

#250 Bugs Marwa
  Admin-app/src/components/Chat/Chat.css
  Admin-app/src/components/Chat/index.js
  Admin-app/src/components/SignIn/index.js
  Admin-app/src/components/SignUp/index.js
  Client-app/src/App.js
  Client-app/src/components/AppBody/index.js
  Client-app/src/components/Chat/Chat.css
  Client-app/src/components/Chat/index.js
  Client-app/src/components/ClientProfile/ClientProfile.css
  Client-app/src/components/ClientProfile/ProfileEditModal.js
  Client-app/src/components/ClientProfile/index.js
  Client-app/src/components/Dashboard/index.js
  Client-app/src/components/Diary/DiaryTable.css
  Client-app/src/components/DoctorInfo/index.js
  Client-app/src/components/Navbar/Navbar.css
  Client-app/src/components/Navbar/index.js
  Client-app/src/components/Notifications/Notifications.css
  Client-app/src/components/QR/QR.css
  Client-app/src/components/SignIn/index.js
  Client-app/src/components/SignIn/signin.css
  Client-app/src/components/SignUp/SignUp.css
  Client-app/src/components/SignUp/index.js
  Client-app/src/components/SymptomsTable/SymptomsTable.css
  Client-app/src/components/SymptomsTable/index.js
  Client-app/src/components/UpdateStatus/UpdateStatus.css
  Client-app/src/index.js
  Client-app/src/screens/Appointment/index.js
  Client-app/src/screens/Chatting/index.js
  Client-app/src/screens/Dashboard/index.js
  Client-app/src/screens/Diary/index.js
  Client-app/src/screens/MyDoctor/index.js
  Client-app/src/screens/Notifications/index.js
  Client-app/src/screens/Profile/index.js
  Client-app/src/screens/QR/index.js
  Client-app/src/screens/Status/index.js
  Client-app/src/screens/Symptoms/index.js
  wiki_docs/USB/Team14_User_Story_Backlog_Sprint_3.xlsx
Labels: Pull Request

#259 Admin patient list
  Admin-app/src/screens/Dashboard/Dashboard.css
  Admin-app/src/screens/Dashboard/Dashboard.test.js
  Admin-app/src/screens/Dashboard/index.js
Labels: Pull Request

#269 Refactor change DB collections used for Issue #266
  Admin-app/src/App.js
  Admin-app/src/backend/firebaseAdminUtilities.js
  Admin-app/src/backend/firebaseDoctorUtilities.js
  Admin-app/src/backend/firebasePatientUtilities.js
  Admin-app/src/backend/firebaseUtilities.js
  Admin-app/src/components/DoctorList/index.js
  Admin-app/src/components/DropdownDoctor/index.js
  Admin-app/src/components/DropdownStatus/index.js
  Admin-app/src/components/PatientList/Patients-Table.css
  Admin-app/src/components/PatientList/index.js
  Admin-app/src/components/PatientProfile/index.js
  Admin-app/src/components/SignUp/index.js
  Admin-app/src/screens/Dashboard/index.js
  Client-app/src/components/SignUp/index.js
Labels: Pull Request

#293 Tushar case sen email bug fix
  Admin-app/src/components/SignIn/index.js
  Admin-app/src/components/SignUp/index.js
  Client-app/src/components/SignIn/index.js
  Client-app/src/components/SignUp/index.js
Labels: Pull Request, prio:high

#294 Bug Fixes #280 #281 - error msg is now correct
  Admin-app/src/components/SignIn/index.js
  Client-app/src/components/SignIn/index.js
Labels: Pull Request, prio:high

#291 Bug fix for the incorrect dob format when editing a profile
  Client-app/src/components/ClientProfile/ProfileEditModal.js
Labels: Pull Request

#298 Bugs #282 #283 and #284
  Admin-app/package-lock.json
  Admin-app/package.json
  Admin-app/src/App.js
  Admin-app/src/components/Navbar/index.js
  Admin-app/src/components/PatientProfile/index.js
  Admin-app/src/components/Sidebar/index.js
  Admin-app/src/components/SidebarItems/SidebarItems.css
  Admin-app/src/components/SidebarItems/index.js
  Admin-app/src/components/SignIn/index.js
  Admin-app/src/components/SignUp/index.js
  Client-app/package-lock.json
  Client-app/package.json
  Client-app/src/backend/firebaseUtilities.js
  Client-app/src/components/BottomNav/BottomNav.css
  Client-app/src/components/Chat/Chat.css
  Client-app/src/components/Navbar/index.js
  Client-app/src/components/SignIn/index.js
  Client-app/src/components/SignUp/index.js
  package.json
Labels: Pull Request

#292 Admin list
  Admin-app/src/App.js
  Admin-app/src/backend/firebaseAdminUtilities.js
  Admin-app/src/components/AdminList/AdminList.css
  Admin-app/src/components/AdminList/EachRow.js
  Admin-app/src/components/AdminList/index.js
  Admin-app/src/components/PatientList/Patients-Table.css
  Admin-app/src/components/SidebarItems/index.js
  Admin-app/src/components/SignIn/index.js
  Admin-app/src/components/SignUp/index.js
Labels: Pull Request

#288 Redux store for doctors
  Admin-app/package-lock.json
  Admin-app/package.json
  Admin-app/src/App.js
  Admin-app/src/store/authSlice.js
  Admin-app/src/store/userInfoSlice.js
  Client-app/src/App.js
  Client-app/src/components/ClientProfile/ProfileEditModal.js
  Client-app/src/components/ClientProfile/index.js
  Client-app/src/components/DoctorInfo/DoctorInfo.css
  Client-app/src/components/DoctorInfo/DoctorInfo.test.js
  Client-app/src/components/DoctorInfo/index.js
  Client-app/src/components/UpdateStatus/StatusModal.js
  Client-app/src/components/UpdateStatus/SymptomsTable.js
  Client-app/src/components/UpdateStatus/index.js
  Client-app/src/store/authSlice.js
  Client-app/src/store/userInfoSlice.js
Labels: Pull Request

#302 Recovery cases
  Admin-app/src/backend/firebasePatientUtilities.js
  Admin-app/src/components/AdminList/EachRow.js
  Admin-app/src/components/AdminList/index.js
  Admin-app/src/components/COVID-19Button/COVID-19Button.css
  Admin-app/src/components/Charts/DoughnutChart.js
  Admin-app/src/components/Charts/DoughtnutChart.css
  Admin-app/src/components/DashboardStats/index.js
  Admin-app/src/components/DropdownStatus/index.js
  Admin-app/src/components/PatientList/SingleRow.js
  Admin-app/src/components/PatientList/index.js
  Admin-app/src/components/PatientProfile/index.js
  Admin-app/src/components/UpcomingEvents/UpcomingEvents.css
  Admin-app/src/components/UpcomingEvents/UpcomingEvents.test.js
  Admin-app/src/components/UpcomingEvents/index.js
  Admin-app/src/screens/Dashboard/index.js
Labels: Pull Request

#304 Adding changes from develop to main
  Admin-app/.firebase/hosting.YnVpbGQ.cache
  Admin-app/.firebaserc
  Admin-app/package-lock.json
  Admin-app/package.json
  Admin-app/src/App.js
  Admin-app/src/backend/firebaseAdminUtilities.js
  Admin-app/src/backend/firebaseDoctorUtilities.js
  Admin-app/src/backend/firebasePatientUtilities.js
  Admin-app/src/backend/firebasePopulateUtilities.js
  Admin-app/src/backend/firebaseUtilities.js
  Admin-app/src/components/AdminList/AdminList.css
  Admin-app/src/components/AdminList/EachRow.js
  Admin-app/src/components/AdminList/index.js
  Admin-app/src/components/COVID-19Button/COVID-19Button.css
  Admin-app/src/components/Charts/DoughnutChart.js
  Admin-app/src/components/Charts/DoughtnutChart.css
  Admin-app/src/components/DashboardStats/index.js
  Admin-app/src/components/DoctorList/index.js
  Admin-app/src/components/DropdownDoctor/index.js
  Admin-app/src/components/DropdownStatus/index.js
  Admin-app/src/components/Navbar/index.js
  Admin-app/src/components/PatientList/Patients-Table.css
  Admin-app/src/components/PatientList/SingleRow.js
  Admin-app/src/components/PatientList/index.js
  Admin-app/src/components/PatientProfile/index.js
  Admin-app/src/components/Sidebar/index.js
  Admin-app/src/components/SidebarItems/SidebarItems.css
  Admin-app/src/components/SidebarItems/index.js
  Admin-app/src/components/SignIn/index.js
  Admin-app/src/components/SignUp/index.js
  Admin-app/src/components/UpcomingEvents/UpcomingEvents.css
  Admin-app/src/components/UpcomingEvents/UpcomingEvents.test.js
  Admin-app/src/components/UpcomingEvents/index.js
  Admin-app/src/screens/Dashboard/Dashboard.css
  Admin-app/src/screens/Dashboard/Dashboard.test.js
  Admin-app/src/screens/Dashboard/index.js
  Admin-app/src/store/authSlice.js
  Admin-app/src/store/userInfoSlice.js
  Client-app/.firebase/hosting.YnVpbGQ.cache
  Client-app/.firebaserc
  Client-app/package-lock.json
  Client-app/package.json
  Client-app/src/App.js
  Client-app/src/backend/firebaseUtilities.js
  Client-app/src/components/BottomNav/BottomNav.css
  Client-app/src/components/Chat/Chat.css
  Client-app/src/components/ClientProfile/ProfileEditModal.js
  Client-app/src/components/ClientProfile/index.js
  Client-app/src/components/DoctorInfo/DoctorInfo.css
  Client-app/src/components/DoctorInfo/DoctorInfo.test.js
  Client-app/src/components/DoctorInfo/index.js
  Client-app/src/components/Navbar/index.js
  Client-app/src/components/SignIn/index.js
  Client-app/src/components/SignUp/index.js
  Client-app/src/components/UpdateStatus/StatusModal.js
  Client-app/src/components/UpdateStatus/SymptomsTable.js
  Client-app/src/components/UpdateStatus/index.js
  Client-app/src/store/authSlice.js
  Client-app/src/store/userInfoSlice.js
  package.json
Labels: Pull Request

#322 Fixed Table Pagination Text Color
  Admin-app/src/components/AdminList/index.js
  Admin-app/src/components/DoctorList/index.js
  Admin-app/src/components/PatientList/index.js
Labels: Pull Request

#296 Steve/140 symptoms admin
  Admin-app/src/backend/firebasePatientUtilities.js
  Admin-app/src/backend/firebaseUtilities.js
  Admin-app/src/components/DropdownStatus/index.js
  Admin-app/src/components/PatientProfile/PatientProfile.css
  Admin-app/src/components/PatientProfile/PatientProfile.test.js
  Admin-app/src/components/PatientProfile/index.js
Labels: Pull Request

#305 QR scanner fix
  Admin-app/src/components/QR/index.js
  Client-app/src/components/BottomNav/BottomNav.css
  Client-app/src/components/Chat/Chat.css
  Client-app/src/components/Chat/index.js
Labels: Pull Request

#324 Status reupdate notification
  Admin-app/cypress/integration/FinalQA.spec.js
  Admin-app/package-lock.json
  Admin-app/package.json
  Admin-app/src/backend/firebaseDoctorUtilities.js
  Admin-app/src/backend/firebasePatientUtilities.js
  Admin-app/src/components/DropdownStatus/index.js
  Admin-app/src/components/Notifications/Notifications.css
  Admin-app/src/components/Notifications/Notifications.test.js
  Admin-app/src/components/Notifications/index.js
  Client-app/cypress/integration/FinalQA.spec.js
  Client-app/src/App.js
  Client-app/src/components/AppBody/index.js
  Client-app/src/components/BottomNav/BottomNav.css
  Client-app/src/components/BottomNav/index.js
  Client-app/src/components/ClientProfile/ClientProfile.css
  Client-app/src/components/ClientProfile/index.js
  Client-app/src/components/UpdateStatus/StatusModal.js
  Client-app/src/components/UpdateStatus/SymptomsTable.js
  Client-app/src/components/UpdateStatus/UpdateStatus.css
  Client-app/src/components/UpdateStatus/index.js
Labels: Pull Request

#325 Client's Notifications
  Admin-app/package-lock.json
  Admin-app/package.json
  Admin-app/src/components/Notifications/Notifications.css
  Admin-app/src/components/PatientProfile/index.js
  Client-app/package-lock.json
  Client-app/package.json
  Client-app/src/backend/firebasePatientUtilities.js
  Client-app/src/backend/firebaseUtilities.js
  Client-app/src/components/Notifications/Notifications.css
  Client-app/src/components/Notifications/Notifications.test.js
  Client-app/src/components/Notifications/index.js
Labels: Pull Request
